### ISSUE TITLE
Current State

### ISSUE THREAD

**Issue by lemonmojo** [royalapplications/beyondnet#1]
## Target Languages
- [x] Unmanaged C#
- [x] C
- [x] Swift
- [x] Kotlin
- [ ] Rust
- [ ] go (There's a sample in the repo that uses manual C to go bindings)

## Types
- [x] Classes
- [x] Structs
- [x] Enums
- [x] Primitives
- [x] Booleans
- [x] [Interfaces](https://github.com/royalapplications/beyondnet/issues/35)
- [x] [Delegates](https://github.com/royalapplications/beyondnet/issues/7)
- [x] Events
- [x] "Typed" Arrays
- [x] [Multidimensional Arrays](https://github.com/royalapplications/beyondnet/issues/72)
- [x] `out` method parameters
- [x] [`ref` arguments](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref)
- [ ] `ref` arguments in delegates
- [x] `ref` return values
- [ ] `ref` return values in delegates
- [x] [`in` arguments](https://github.com/royalapplications/beyondnet/issues/43)
- [ ] `in` arguments in delegates
- [x] Generic Methods (Only experimental support)
- [x] Generic Types (Only experimental support)
- [x] Tuples (Comes free with generic types support)
- [x] [Nullable structs](https://github.com/royalapplications/beyondnet/issues/63) (ie. `Guid?`/`Nullable<Guid>`) 
- [ ] [Nullable primitives](https://github.com/royalapplications/beyondnet/issues/63)
- [ ] [Nullable enums](https://github.com/royalapplications/beyondnet/issues/63)
- [ ] Managed Pointers (ie. `char*`)
- [ ] Ref Structs (impossible?)

## Language Constructs
- [x] Constructors
- [x] Destructors
- [x] Methods
- [x] [Extension Methods](https://stackoverflow.com/a/299526/1025706)
- [x] Properties (Getters/Setters)
- [x] Fields (Getters/Setters)
- [x] Exception handling
- [x] Overloads
- [x] [Type Conversion (Casting/`as`)](https://github.com/royalapplications/beyondnet/issues/13)
- [x] [Type checks (`is`)](https://github.com/royalapplications/beyondnet/issues/13)
- [x] [Boxing/Unboxing of primitives (Int32 <-> System.Object)](https://github.com/royalapplications/beyondnet/issues/13)
- [x] [Indexers](https://github.com/royalapplications/beyondnet/issues/29)
- [x] [Nullability](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.nullabilityinfocontext?view=net-7.0)
- [ ] Async stuff

## Target Platforms for automatic build support
- [x] macOS ARM64
- [x] macOS x64
- [x] iOS ARM64
- [x] iOS Simulator ARM64
- [x] iOS Simulator x64
- [ ] [tvOS ARM64](https://github.com/royalapplications/beyondnet/issues/34)
- [ ] [watchOS (?)](https://github.com/royalapplications/beyondnet/issues/34)
- [ ] [visionOS ARM64](https://github.com/royalapplications/beyondnet/issues/34)
- [ ] [visionOS Simulator ARM64](https://github.com/royalapplications/beyondnet/issues/34)
- [ ] [Android](https://github.com/royalapplications/beyondnet/issues/34)
- [ ] [Linux ARM64](https://github.com/royalapplications/beyondnet/issues/34)
- [ ] [Linux x64](https://github.com/royalapplications/beyondnet/issues/34)

## Misc
- [ ] Stable ABI (We're far from the point where we can ensure that the generated code will be binary compatible from one version of the generator to the next)

**Comment by brunck** [comment]
@damianmehers have you seen this repo?
