### ISSUE TITLE
Swift Enhancements

### ISSUE THREAD

**Issue by lemonmojo** [royalapplications/beyondnet#27]
- [ ] [Generate Swift protocols for C# interfaces and use instead of the impl objects](https://github.com/lemonmojo/NativeAOTLibraryTest/issues/35)
- [x] Can we get [type safe arrays](https://github.com/royalapplications/beyondnet/issues/70) to work?
- [x] Maybe map specific array types to a generic DNArray<T> Swift type and implement indexing
  - [x] Used another approach to implement iterating over .NET arrays in Swift
- [ ] Can we map C# generics to swift generics?
- [x] [Make Swift properties and fields nicer](https://github.com/lemonmojo/NativeAOTLibraryTest/issues/36)
- [x] Maybe we can nest types using [nested type aliases](https://www.swiftbysundell.com/articles/namespacing-swift-code-with-nested-types)

**Comment by lemonmojo** [comment]
Closing this in favor of individual issues.
