### ISSUE TITLE
Kotlin To-Do's

### ISSUE THREAD

**Issue by lemonmojo** [royalapplications/beyondnet#81]
- [ ] Ensure unsigned integers are handled correctly (see https://www.mkammerer.de/blog/jna-and-unsigned-integers/)
- [ ] Interfaces (Kotlin supports default interface implementations, so it's likely that the same approach that we use for Swift works)
- [ ] Casting/Type Checking
- [ ] By ref arguments
- [ ] Boxing/Unbixing
- [ ] Arrays
- [ ] Delegates/Events
- [ ] Typealiases to restore namespace hierarchy
